#!/usr/bin/env python

#
# Copyright (c) 2015 University of Cambridge
# All rights reserved.
#
# This software was developed by Stanford University and the University of Cambridge Computer Laboratory 
# under National Science Foundation under Grant No. CNS-0855268,
# the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
# by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"), 
# as part of the DARPA MRC research programme.
#
# Use of this source code is governed by the Apache 2.0 license; see LICENSE file
#

from subprocess import Popen, PIPE

proc = Popen(["ifconfig","eth2","192.168.100.1"], stdout=PIPE)
#proc = Popen(["ifconfig","eth3","192.168.101.1"], stdout=PIPE)
proc = Popen(["ifconfig","nf0","192.168.200.1"], stdout=PIPE)
proc = Popen(["ifconfig","nf1","192.168.201.1"], stdout=PIPE)
proc = Popen(["ifconfig","nf2","192.168.202.1"], stdout=PIPE)
proc = Popen(["ifconfig","nf3","192.168.203.1"], stdout=PIPE)

